import { Inter } from "next/font/google";
import "./globals.css";

import { StoreProvider } from "@/store/StoreProvider";
import { HeaderTemplate } from "@/components/template/header-template";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={inter.className}>
          <div className="flex flex-col bg-white overflow-hidden w-full max-w-7xl mx-auto px-4 md:px-4 ">
            <HeaderTemplate />
            {children}
          </div>
        </body>
      </html>
    </StoreProvider>
  );
}
